project_id = "ehhgzzkmvlzhntvvngpf"

[functions.sync-google-sheets]
verify_jwt = false

[functions.fetch-gmail]
verify_jwt = false

[functions.fetch-slack]
verify_jwt = false

[functions.tag-updates]
verify_jwt = false